export const MOVIE_COMMENT_REQUEST = "MOVIE_COMMENT_REQUEST";
export const MOVIE_COMMENT_SUCCESS = "MOVIE_COMMENT_SUCCESS";
export const MOVIE_COMMENT_FAIL = "MOVIE_COMMENT_FAIL";

export const MOVIE_GET_COMMENTS_REQUEST = "MOVIE_GET_COMMENTS_REQUEST";
export const MOVIE_GET_COMMENTS_SUCCESS = "MOVIE_GET_COMMENTS_SUCCESS";
export const MOVIE_GET_COMMENTS_FAIL = "MOVIE_GET_COMMENTS_FAIL";
